FROM php:7.3.8-fpm-alpine3.10 AS base
WORKDIR /var/www
COPY application /var/www
RUN docker-php-ext-install pdo_mysql

FROM composer:1.8.6 AS build
COPY application /application
WORKDIR /application


FROM build AS development_build
RUN composer install -v


FROM base AS debug
RUN apk add --no-cache $PHPIZE_DEPS
RUN pecl install xdebug-2.7.2
RUN docker-php-ext-enable xdebug
RUN apk del --purge $PHPIZE_DEPS
COPY docker/runtime/debug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini


FROM debug AS development
RUN mv /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
RUN rm /usr/local/etc/php/php.ini-production
COPY --from=development_build /application/vendor /var/www/vendor


FROM build AS production_build
RUN composer install -v --no-dev --optimize-autoloader


FROM base AS production
RUN mv /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
RUN rm /usr/local/etc/php/php.ini-development
COPY --from=production_build /application/vendor /var/www/vendor
RUN rm composer.json
