version: '3.7'
services:
  database:
    container_name: application_database
    image: mysql:5.7
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./database/volume:/var/lib/mysql
    env_file:
      - ./database/.env

  webserver:
    container_name: application_webserver
    build:
      context: ..
      dockerfile: docker/webserver/dockerfile
      target: base
    depends_on:
      - runtime
    ports:
      - 443:443
      - 80:80
    volumes:
      - ../application:/var/www
      - ./webserver/default.conf:/etc/nginx/conf.d/default.conf

  runtime:
    container_name: application_runtime
    build:
      context: ..
      dockerfile: docker/runtime/dockerfile
      target: development
    volumes:
      - ../application:/var/www
    env_file:
      - ./runtime/.env
    expose:
      - 9000
      - 9001
    depends_on:
      - database
    links:
      - database
