version: "3"

services:
  proxy:
    image: nginx:1.21.3-alpine
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - proxy

  api:
    image: node:16.12.0-alpine3.14
    user: node
    working_dir: /home/node/api
    volumes:
      - ../api:/home/node/api
    networks:
      - api
      - proxy
    # tty: true
    command: [ 'npm', 'run', 'start:dev' ]

  web:
    image: node:16.12.0-alpine3.14
    user: node
    working_dir: /home/node/web
    volumes:
      - ../web:/home/node/web
    networks:
      - proxy
    # tty: true
    command: [ 'npm', 'run', 'dev' ]

  database:
    image: postgres:14.0-alpine3.14
    environment:
      POSTGRES_PASSWORD: CHANGEME
      POSTGRES_USER: CHANGEME
      POSTGRES_DB: CHANGEME
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - api

volumes:
  database:

networks:
  api:
  proxy:
